### ISSUE TITLE
The Complexity of BF.ADD is O(log N), N represents for what?

### ISSUE THREAD

**Issue by chxfantasy** [RedisLabsModules/redisbloom#61]
Hi, sorry for this question.

The complexity of bloom filter algorithm when add or query values is O(K), where K represents the number of hash functions.

The Complexity of BF.ADD is O(log N), N represents for what?

**Comment by mnunberg** [comment]
N is the number of stacked filters; or in other words, the number of times the filter capacity needs to be increased
